FROM node:latest

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet
COPY ./ ./

# Commande pour démarrer l'application en mode développement
CMD ["npm", "run", "start:dev", "--", "--host", "0.0.0.0"]